### ISSUE TITLE
Reset project repo :(

### ISSUE THREAD

**Issue by emilianoeloi** [ci-dashboard/gitlab-ci-dashboard#1]
Very Sorry but I needded to reset the project because I commit a credential. https://github.com/isaacs/github/issues/253
cc: @marek-ganko

**Comment by marek-ganko** [comment]
Did you tried to rebase the master branch?

**Comment by emilianoeloi** [comment]
Yes. I rewrote all tree, but I couldn't erase a mention on Issue

**Comment by marek-ganko** [comment]
Oh Maybe it needs to be changed through github UI. Anyhow, you can always recreate the issues here and push the modified local repo.

**Comment by emilianoeloi** [comment]
see a sample of the problem: https://github.com/emilianoeloi/git/issues/1

**Comment by dennisdegreef** [comment]
Have you thought about changing the credential as an alternative?
