### ISSUE TITLE
Cannot find property 'id' of undefined when  run as Standalone using --config parameter

### ISSUE THREAD

**Issue by vijayjangid** [ci-dashboard/gitlab-ci-dashboard#4]
As a user,

When I am running below command 
gitlab-ci-dashbaord --config ./config.json

It opens a browser window and shows the error "Cannot find property 'id' of undefined".
After debugging I found that the issue is happening because of **line: 423** in **main.js** file where it try to fetch the lastPipelineId and fails.

Due to this, the dashboard does not show any project status.

However running application as
gitlab-ci-dashboard --gitlab <gitlab> --token <token> --projectFile <projectFile> 
works perfectly fine.

Could someone please look into this.

Please let me know if you need more details.

**Comment by aponski** [comment]
I have the same problem running application as 
gitlab-ci-dashboard --gitlab --token --projectFile 

`Something went wrong. Make sure the configuration is ok and your Gitlab is up and running. Details: Cannot read property 'id' of null`
